version: '3.4'

services:
  apigootax:
    image: apigootax
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3333:3333
